<?php

namespace AppBundle\Repository;

/**
 * BankWireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankWireRepository extends \Doctrine\ORM\EntityRepository
{
}
