<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * BookmakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmakerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBookmakers($firstResult = 0, $maxResult = 10, $search = '', $state = '')
    {
        $qd = $this->createQueryBuilder('bookmaker');
        $qd
            ->setFirstResult($firstResult)
            ->setMaxResults($maxResult)
        ;

        if ($search !== '') {
            $qd->andWhere('bookmaker.name LIKE :search')
                ->setParameter('search', "%".$search."%");
        }

        if ($state !== '') {
            $qd->andWhere('bookmaker.visible = :state')
                ->setParameter('state', $state);
        }

        $qd->orderBy('bookmaker.name', 'asc');

        $paginator = new Paginator($qd);

        return $paginator;
    }
}
