<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * ChampionshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionshipRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChampionships($sportId, $firstResult = 0, $maxResult = 10, $search = '', $state = '', $paginator = true)
    {
        if (!is_int($sportId)) {
            throw new \Exception('sportId must be a int value');
        }

        $qb = $this->createQueryBuilder('championship');
        $qb
            ->where('championship.sport = :sportId')
            ->setParameter('sportId', $sportId);
            
        if ($maxResult > 0)    
            $qb->setFirstResult($firstResult)
            ->setMaxResults($maxResult);

        if ($search !== '') {
            $qb->andWhere('championship.name LIKE :search')
                ->setParameter('search', "%".$search."%");
        }

        if ($state !== '') {
            $qb->andWhere('championship.visible = :state')
                ->setParameter('state', $state);
        }

        $qb->orderBy('championship.name', 'asc');

        if ($paginator === false) {
            return $qb->getQuery()->getResult();
        }

        $paginator = new Paginator($qb);

        return $paginator;
    }
}
