<?php

namespace AppBundle\Repository;

/**
 * SportBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportBetRepository extends \Doctrine\ORM\EntityRepository
{
}
