<?php

namespace AppBundle\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findEndedSubscriptions()
    {
        $qd = $this->createQueryBuilder('s');
        $qd->where('s.finishedAt < :now')
            ->setParameter(':now', new \DateTime());

        $query = $qd->getQuery();

        return $query->getResult();
    }
}
