<?php

namespace AppBundle\Repository;

/**
 * TipsterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipsterRepository extends \Doctrine\ORM\EntityRepository
{
}
