# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    oauth.user_provider:
        class: AppBundle\Service\UserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    mangopay:
        class: AppBundle\Service\MangoPayService
        arguments: ["%mangopay_client_id%", "%mangopay_passphrase%", "%kernel.root_dir%", "@doctrine.orm.entity_manager", "@session", "@router", "@logger", "@security.token_storage"]

    aws:
        class: AppBundle\Service\AWSService
        arguments: ["%aws_key%", "%aws_secret%", "%aws_region%", "%aws_version%", "%aws_sender_id%"]

    aws_s3.client:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: latest
                region: "%aws_region%"
                credentials:
                    key: "%aws_key%"
                    secret: "%aws_secret%"